// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main_server_to_client.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_main_5fserver_5fto_5fclient_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_main_5fserver_5fto_5fclient_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_main_5fserver_5fto_5fclient_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_main_5fserver_5fto_5fclient_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_main_5fserver_5fto_5fclient_2eproto;
namespace ChampionFist {
class S_Start;
class S_StartDefaultTypeInternal;
extern S_StartDefaultTypeInternal _S_Start_default_instance_;
}  // namespace ChampionFist
PROTOBUF_NAMESPACE_OPEN
template<> ::ChampionFist::S_Start* Arena::CreateMaybeMessage<::ChampionFist::S_Start>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ChampionFist {

enum ServerCommandType : int {
  S_START = 0,
  ServerCommandType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ServerCommandType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ServerCommandType_IsValid(int value);
constexpr ServerCommandType ServerCommandType_MIN = S_START;
constexpr ServerCommandType ServerCommandType_MAX = S_START;
constexpr int ServerCommandType_ARRAYSIZE = ServerCommandType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ServerCommandType_descriptor();
template<typename T>
inline const std::string& ServerCommandType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ServerCommandType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ServerCommandType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ServerCommandType_descriptor(), enum_t_value);
}
inline bool ServerCommandType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ServerCommandType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ServerCommandType>(
    ServerCommandType_descriptor(), name, value);
}
// ===================================================================

class S_Start PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ChampionFist.S_Start) */ {
 public:
  inline S_Start() : S_Start(nullptr) {}
  virtual ~S_Start();

  S_Start(const S_Start& from);
  S_Start(S_Start&& from) noexcept
    : S_Start() {
    *this = ::std::move(from);
  }

  inline S_Start& operator=(const S_Start& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Start& operator=(S_Start&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const S_Start& default_instance();

  static inline const S_Start* internal_default_instance() {
    return reinterpret_cast<const S_Start*>(
               &_S_Start_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(S_Start& a, S_Start& b) {
    a.Swap(&b);
  }
  inline void Swap(S_Start* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Start* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_Start* New() const final {
    return CreateMaybeMessage<S_Start>(nullptr);
  }

  S_Start* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_Start>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_Start& from);
  void MergeFrom(const S_Start& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_Start* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ChampionFist.S_Start";
  }
  protected:
  explicit S_Start(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_main_5fserver_5fto_5fclient_2eproto);
    return ::descriptor_table_main_5fserver_5fto_5fclient_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGameServerIpFieldNumber = 1,
    kGameServerPortFieldNumber = 2,
  };
  // string game_server_ip = 1;
  void clear_game_server_ip();
  const std::string& game_server_ip() const;
  void set_game_server_ip(const std::string& value);
  void set_game_server_ip(std::string&& value);
  void set_game_server_ip(const char* value);
  void set_game_server_ip(const char* value, size_t size);
  std::string* mutable_game_server_ip();
  std::string* release_game_server_ip();
  void set_allocated_game_server_ip(std::string* game_server_ip);
  private:
  const std::string& _internal_game_server_ip() const;
  void _internal_set_game_server_ip(const std::string& value);
  std::string* _internal_mutable_game_server_ip();
  public:

  // int32 game_server_port = 2;
  void clear_game_server_port();
  ::PROTOBUF_NAMESPACE_ID::int32 game_server_port() const;
  void set_game_server_port(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_game_server_port() const;
  void _internal_set_game_server_port(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:ChampionFist.S_Start)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr game_server_ip_;
  ::PROTOBUF_NAMESPACE_ID::int32 game_server_port_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_main_5fserver_5fto_5fclient_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// S_Start

// string game_server_ip = 1;
inline void S_Start::clear_game_server_ip() {
  game_server_ip_.ClearToEmpty();
}
inline const std::string& S_Start::game_server_ip() const {
  // @@protoc_insertion_point(field_get:ChampionFist.S_Start.game_server_ip)
  return _internal_game_server_ip();
}
inline void S_Start::set_game_server_ip(const std::string& value) {
  _internal_set_game_server_ip(value);
  // @@protoc_insertion_point(field_set:ChampionFist.S_Start.game_server_ip)
}
inline std::string* S_Start::mutable_game_server_ip() {
  // @@protoc_insertion_point(field_mutable:ChampionFist.S_Start.game_server_ip)
  return _internal_mutable_game_server_ip();
}
inline const std::string& S_Start::_internal_game_server_ip() const {
  return game_server_ip_.Get();
}
inline void S_Start::_internal_set_game_server_ip(const std::string& value) {
  
  game_server_ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void S_Start::set_game_server_ip(std::string&& value) {
  
  game_server_ip_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ChampionFist.S_Start.game_server_ip)
}
inline void S_Start::set_game_server_ip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  game_server_ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ChampionFist.S_Start.game_server_ip)
}
inline void S_Start::set_game_server_ip(const char* value,
    size_t size) {
  
  game_server_ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ChampionFist.S_Start.game_server_ip)
}
inline std::string* S_Start::_internal_mutable_game_server_ip() {
  
  return game_server_ip_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* S_Start::release_game_server_ip() {
  // @@protoc_insertion_point(field_release:ChampionFist.S_Start.game_server_ip)
  return game_server_ip_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void S_Start::set_allocated_game_server_ip(std::string* game_server_ip) {
  if (game_server_ip != nullptr) {
    
  } else {
    
  }
  game_server_ip_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), game_server_ip,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ChampionFist.S_Start.game_server_ip)
}

// int32 game_server_port = 2;
inline void S_Start::clear_game_server_port() {
  game_server_port_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 S_Start::_internal_game_server_port() const {
  return game_server_port_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 S_Start::game_server_port() const {
  // @@protoc_insertion_point(field_get:ChampionFist.S_Start.game_server_port)
  return _internal_game_server_port();
}
inline void S_Start::_internal_set_game_server_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  game_server_port_ = value;
}
inline void S_Start::set_game_server_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_game_server_port(value);
  // @@protoc_insertion_point(field_set:ChampionFist.S_Start.game_server_port)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ChampionFist

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ChampionFist::ServerCommandType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ChampionFist::ServerCommandType>() {
  return ::ChampionFist::ServerCommandType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_main_5fserver_5fto_5fclient_2eproto
