// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameClientToServer.proto

#include "GameClientToServer.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ChampionFist {
PROTOBUF_CONSTEXPR C_Connect::C_Connect(
    ::_pbi::ConstantInitialized)
  : name_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , seat_no_(0){}
struct C_ConnectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_ConnectDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_ConnectDefaultTypeInternal() {}
  union {
    C_Connect _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_ConnectDefaultTypeInternal _C_Connect_default_instance_;
}  // namespace ChampionFist
static ::_pb::Metadata file_level_metadata_GameClientToServer_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_GameClientToServer_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_GameClientToServer_2eproto = nullptr;

const uint32_t TableStruct_GameClientToServer_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ChampionFist::C_Connect, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ChampionFist::C_Connect, name_),
  PROTOBUF_FIELD_OFFSET(::ChampionFist::C_Connect, seat_no_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ChampionFist::C_Connect)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ChampionFist::_C_Connect_default_instance_._instance,
};

const char descriptor_table_protodef_GameClientToServer_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030GameClientToServer.proto\022\014ChampionFist"
  "\"*\n\tC_Connect\022\014\n\004name\030\001 \001(\t\022\017\n\007seat_no\030\002"
  " \001(\005*p\n\021ClientCommandType\022\013\n\007C_EMPTY\020\000\022\r"
  "\n\tC_CONNECT\020\001\022\n\n\006C_LOAD\020\002\022\n\n\006C_EXIT\020\003\022\017\n"
  "\013C_OPERATION\020\004\022\013\n\007C_START\020\005\022\t\n\005C_END\020\006b\006"
  "proto3"
  ;
static ::_pbi::once_flag descriptor_table_GameClientToServer_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_GameClientToServer_2eproto = {
    false, false, 206, descriptor_table_protodef_GameClientToServer_2eproto,
    "GameClientToServer.proto",
    &descriptor_table_GameClientToServer_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_GameClientToServer_2eproto::offsets,
    file_level_metadata_GameClientToServer_2eproto, file_level_enum_descriptors_GameClientToServer_2eproto,
    file_level_service_descriptors_GameClientToServer_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_GameClientToServer_2eproto_getter() {
  return &descriptor_table_GameClientToServer_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_GameClientToServer_2eproto(&descriptor_table_GameClientToServer_2eproto);
namespace ChampionFist {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ClientCommandType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_GameClientToServer_2eproto);
  return file_level_enum_descriptors_GameClientToServer_2eproto[0];
}
bool ClientCommandType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class C_Connect::_Internal {
 public:
};

C_Connect::C_Connect(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:ChampionFist.C_Connect)
}
C_Connect::C_Connect(const C_Connect& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    name_.Set(from._internal_name(), 
      GetArenaForAllocation());
  }
  seat_no_ = from.seat_no_;
  // @@protoc_insertion_point(copy_constructor:ChampionFist.C_Connect)
}

inline void C_Connect::SharedCtor() {
name_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  name_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
seat_no_ = 0;
}

C_Connect::~C_Connect() {
  // @@protoc_insertion_point(destructor:ChampionFist.C_Connect)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C_Connect::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  name_.Destroy();
}

void C_Connect::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void C_Connect::Clear() {
// @@protoc_insertion_point(message_clear_start:ChampionFist.C_Connect)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty();
  seat_no_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_Connect::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ChampionFist.C_Connect.name"));
        } else
          goto handle_unusual;
        continue;
      // int32 seat_no = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          seat_no_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C_Connect::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ChampionFist.C_Connect)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ChampionFist.C_Connect.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // int32 seat_no = 2;
  if (this->_internal_seat_no() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_seat_no(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ChampionFist.C_Connect)
  return target;
}

size_t C_Connect::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ChampionFist.C_Connect)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // int32 seat_no = 2;
  if (this->_internal_seat_no() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_seat_no());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_Connect::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    C_Connect::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_Connect::GetClassData() const { return &_class_data_; }

void C_Connect::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<C_Connect *>(to)->MergeFrom(
      static_cast<const C_Connect &>(from));
}


void C_Connect::MergeFrom(const C_Connect& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ChampionFist.C_Connect)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _internal_set_name(from._internal_name());
  }
  if (from._internal_seat_no() != 0) {
    _internal_set_seat_no(from._internal_seat_no());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C_Connect::CopyFrom(const C_Connect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ChampionFist.C_Connect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_Connect::IsInitialized() const {
  return true;
}

void C_Connect::InternalSwap(C_Connect* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &name_, lhs_arena,
      &other->name_, rhs_arena
  );
  swap(seat_no_, other->seat_no_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C_Connect::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GameClientToServer_2eproto_getter, &descriptor_table_GameClientToServer_2eproto_once,
      file_level_metadata_GameClientToServer_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ChampionFist
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ChampionFist::C_Connect*
Arena::CreateMaybeMessage< ::ChampionFist::C_Connect >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ChampionFist::C_Connect >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
